[bumpver]
current_version = "0.0.0"
version_pattern = "MAJOR.MINOR.PATCH[.TAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[bumpver.file_patterns]
"configure.ac" = [
    '\[libasdf\], \[{version}\]'
]
"CMakeLists.txt" = [
    'VERSION {version}'
]
"docs/conf.py" = [
    "release = '{version}'"
]
".bumpver.toml" = [
    'current_version = "{version}"',
]

