[tool.towncrier]
name = "libasdf"
version = "0.1.0-alpha0"
directory = "changes"
filename = "CHANGES.rst"
issue_format = "`#{issue} <https://github.com/asdf-format/asdf/issues/{issue}>`_"
wrap = true

[tool.towncrier.fragment.general]
[tool.towncrier.fragment.feature]
[tool.towncrier.fragment.bugfix]
[tool.towncrier.fragment.doc]
[tool.towncrier.fragment.removal]
[tool.towncrier.fragment.misc]
